### ISSUE TITLE
老哥这个项目现在可以爬分省分专业的分数吗

### ISSUE THREAD

**Issue by baifengbai** [Dosrui78/ZSGK#1]

**Comment by Dosrui78** [comment]
可以吧 分数线不就是分省分专业的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Bai Feng ***@***.***>
发送时间: Saturday, December 11, 2021 3:37:36 PM
收件人: Dosrui78/ZSGK ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Dosrui78/ZSGK] 老哥这个项目现在可以爬到分省分专业的数据吗 (Issue #1)


―

**Comment by baifengbai** [comment]
Traceback (most recent call last):
  File "Spider.py", line 139, in <module>
    S.main(count)
  File "Spider.py", line 124, in main
    signsafe = self.getSign(payloadData)
  File "Spider.py", line 57, in getSign
    sign = execjs.compile(js_text_1).call("A", p)
  File "/Users/fengbai/opt/anaconda3/lib/python3.8/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/Users/fengbai/opt/anaconda3/lib/python3.8/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/Users/fengbai/opt/anaconda3/lib/python3.8/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/Users/fengbai/opt/anaconda3/lib/python3.8/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/Users/fengbai/opt/anaconda3/lib/python3.8/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/Users/fengbai/opt/anaconda3/lib/python3.8/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: ReferenceError: "require" is not defined

这个报错是什么原因引起的，对js不是很熟，没有搜到合适的解决办法

**Comment by baifengbai** [comment]
您爬取的数据可以分享一份吗，感恩342741263@qq.com。可否加个微信付费指导一下bai7426，安装完node依赖后能跑了，但是跑了一分钟就出现如下报错：
string indices must be integers
Traceback (most recent call last):
  File "Spider.py", line 154, in <module>
    S.main(count)
  File "Spider.py", line 143, in main
    if content['item']:
TypeError: 'NoneType' object is not subscriptable

**Comment by Dosrui78** [comment]
你要全部数据啊 我也没  会封ip 抓全部要代理的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Bai Feng ***@***.***>
发送时间: Sunday, December 12, 2021 11:01:30 AM
收件人: Dosrui78/ZSGK ***@***.***>
抄送: Ricky ***@***.***>; Comment ***@***.***>
主题: Re: [Dosrui78/ZSGK] 老哥这个项目现在可以爬分省分专业的分数吗 (Issue #1)


***@***.******@***.***>，我爬了另一个网站http://college.gaokao.com/，数据缺失比较多。<http://college.gaokao.com/%EF%BC%8C%E6%95%B0%E6%8D%AE%E7%BC%BA%E5%A4%B1%E6%AF%94%E8%BE%83%E5%A4%9A%E3%80%82>

―

**Comment by baifengbai** [comment]
好的，谢谢

**Comment by Dosrui78** [comment]
加你了
